version: 0.1
tools:
  definitions:
    - name: eslint
      runtime: node
      package: eslint
      shims: [eslint]
      known_good_version: 8.10.0
    - name: eslint_d
      runtime: node
      package: eslint_d
      shims: [eslint_d]
      known_good_version: 13.0.0
lint:
  definitions:
    - name: eslint
      files: [typescript, javascript]
      tools: [eslint, eslint_d, jq]
      commands:
        - name: lint_lsp
          output: eslint
          run: eslint_d --format json ${target}
          error_codes: [2]
          read_output_from: stdout
          parser:
            runtime: python
            run: jq -e
      direct_configs:
        - .eslintrc
        - .eslintrc.cjs
        - .eslintrc.js
        - .eslintrc.json
        - .eslintrc.yaml
        - .eslintrc.yml
      suggest_if: config_present
      affects_cache:
        - .eslintignore
        - package.json
        - tsconfig.json
      issue_url_format: https://eslint.org/docs/rules/{}
      known_good_version: 8.10.0
      version_command:
        parse_regex: ${semver}
        run: eslint --version
