version: 0.1
tools:
  definitions:
    - name: eslint_d
      runtime: node
      package: eslint_d
      shims: [eslint_d]
      known_good_version: 13.0.0
lint:
  definitions:
    - name: eslint_d
      files: [typescript, javascript]
      tools: [eslint_d]
      commands:
        - name: lint
          output: eslint
          run: eslint_d --output-file ${tmpfile} --format json ${target}
          error_codes: [2]
          read_output_from: tmp_file
      direct_configs:
        - .eslintrc
        - .eslintrc.cjs
        - .eslintrc.js
        - .eslintrc.json
        - .eslintrc.yaml
        - .eslintrc.yml
      suggest_if: config_present
      affects_cache:
        - .eslintignore
        - package.json
        - tsconfig.json
      known_good_version: 13.0.0
      version_command:
        parse_regex: ${semver}
        run: eslint_d --version
